---
title: "DF2-Education"
author: "Abhay Prasanna Rao"
date: "2023-12-02"
output: html_document
---

```{r setup_education, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

------------------------------------------------------------------------

## Education

As a data science student, I'm captivated by how education influences economic and societal progress. My analysis focuses on how higher education correlates with improved job prospects and financial stability. With the wealth of educational data available for longitudinal study, I'm keen to understand and potentially shape educational policy. I'm especially interested in how education imparts essential skills for the modern workforce and promotes adaptability in a tech-driven world. Ultimately, my work delves into education's role in fostering individual growth and its potential to drive societal change.

```{r,message=FALSE,warning=FALSE}
#Neha
#Education - K201501
df2 <- get_acs(geography = "state", 
                table = "K201501", 
                year = 2021, 
                survey = "acs1/subject",cache_table = TRUE)

variables_df2 <- data.frame(
  variable = c("K201501_001", "K201501_002", "K201501_003", "K201501_004", "K201501_005", "K201501_006", "K201501_007", "K201501_008"),
  label = c("Education_Total_students", "Education_Below_9th grade", "Education_9th to 12th grade_no diploma", "Education_High_school_graduate", "Education_Some college_no degree", "Education_Associates_degree", "Education_Bachelors_degree", "Education_Graduate_professional degree")
)

df2_labeled <- df2 %>%
  left_join(variables_df2, by = "variable")

df2_wide <- df2_labeled %>%
  pivot_wider(names_from = label, values_from = estimate, id_cols = NAME)
```

**Exploratory Data Analysis (EDA)** based on percentage

```{r,message=FALSE,warning=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)

# Convert df2_wide to long format
df2_long <- df2_wide %>%
  gather(key = "Education_Level", value = "Count", -NAME)

# Calculate total count for each state only once
total_counts <- df2_long %>%
  group_by(NAME) %>%
  summarize(Total = sum(Count)) 

# Join with original data to add the Total column
df2_long <- df2_long %>%
  left_join(total_counts, by = "NAME")

# Calculate the percentage for each education level
df2_long <- df2_long %>%
  mutate(Percentage = (Count / Total) * 100)

# Create graphs for each educational level
unique_levels <- unique(df2_long$Education_Level)
plots <- list()

for (level in unique_levels) {
  df_subset <- filter(df2_long, Education_Level == level)

  p <- ggplot(df_subset, aes(x = NAME, y = Percentage, fill = Education_Level)) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    labs(title = paste("Percentage Distribution of", level, "across States"), 
         x = "State", 
         y = "Percentage") +
    guides(fill = guide_legend(title = "Education Level"))

  plots[[level]] <- p
}

# Print plots (optional)
for (plot in plots) {
  print(plot)
}

```

```{r,message=FALSE,warning=FALSE}
df2_percentages <- df2_wide %>%
  mutate(
    `Education_Below_9th grade_Percentage` = `Education_Below_9th grade` / Education_Total_students * 100,
    `Education_9th to 12th grade_no diploma_Percentage` = `Education_9th to 12th grade_no diploma` / Education_Total_students * 100,
    Education_High_school_graduate_Percentage = Education_High_school_graduate / Education_Total_students * 100,
    `Education_Some college_no degree_Percentage` = `Education_Some college_no degree` / Education_Total_students * 100,
    Education_Associates_degree_Percentage = Education_Associates_degree / Education_Total_students * 100,
    Education_Bachelors_degree_Percentage = Education_Bachelors_degree / Education_Total_students * 100,
    `Education_Graduate_professional degree_Percentage` = `Education_Graduate_professional degree` / Education_Total_students * 100
  )
percentage_columns <- grep("_Percentage$", names(df2_percentages), value = TRUE)
df2_long <- df2_percentages %>%
  pivot_longer(cols = percentage_columns, names_to = "Age_Group", values_to = "Percentage")
ggplot(df2_long, aes(x = reorder(NAME, -Education_Total_students), y = Percentage, fill = Age_Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Age Distribution by State",
       x = "State",
       y = "Percentage of Total Population",
       fill = "Age Group") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 
 
```
**Inference for the above garph**

The bar chart depict the distribution of educational attainment by state, represented as a percentage of the total population within each state. From the graph, we can infer that certain states have a higher percentage of individuals with specific levels of education for instance the states with larger populations, such as California, Texas, Florida, and New York, exhibit the highest numbers in educational attainment across all levels, from below 9th grade to graduate or professional degrees. 
This suggests a diverse educational demand and a corresponding supply of educational institutions and job opportunities that require various levels of education. California stands out with the highest numbers in every category, reflecting its vast and diverse educational landscape. While the prevalence of higher education degrees in states like Illinois denotes a strong higher education system, the significant figures for those with less than a high school diploma highlight ongoing challenges in educational access and retention in these heavily populated states.


```{r,message=FALSE,warning=FALSE}
ggplot(df2_percentages, aes(x = reorder(NAME,`Education_Graduate_professional degree_Percentage`, mean), y = `Education_Graduate_professional degree_Percentage`)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Education Distribution by State",
       x = "State",
       y = "Percentage of people with graduate level degree)")

```
```{r,message=FALSE,warning=FALSE}
ggplot(df2_percentages, aes(x = reorder(NAME,Education_High_school_graduate_Percentage, mean), y = Education_High_school_graduate_Percentage)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Education Distribution by State",
       x = "State",
       y = "Percentage of people with High_School level degree)")


```
```{r,message=FALSE,warning=FALSE}
ggplot(df2_percentages, aes(x = reorder(NAME,Education_Bachelors_degree_Percentage, mean), y = Education_Bachelors_degree_Percentage)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Education Distribution by State",
       x = "State",
       y = "Percentage of people with Bachelors level degree)")

```

**Inference for above Three Graphs**

The above three bar charts illustrate the distribution of various education levels across different states. The first chart likely represents the percentage of the population with a bachelor's degree, showing a gradual increase in educational attainment towards District of columbia states. The second chart appears to show the distribution of master's degrees, which, while following a similar pattern, reflects lower percentages indicative of the reduced number of individuals who pursue postgraduate education. The third chart, presumably depicting high school diploma holders, presents a more pronounced variability, culminating in a steep increase for the last few states. This suggests a greater disparity in high school graduation rates across states. Generally, states with higher percentages of bachelor's and master's degree holders also have a high percentage of high school diploma holders, indicating possible correlations between state education policies and the value placed on education.

------------------------------------------------------------------------