---
title: "DF3-Citizenship"
author: "Abhay Prasanna Rao"
date: "2023-12-02"
output: html_document
---

```{r setup_citizenship, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

------------------------------------------------------------------------

## Citizenship

```{r,message=FALSE}
#Esha
#Citizenship - K200501

df3<- get_acs(
  geography = "state", 
  table = "K200501", 
  year = 2021, 
  survey = "acs1/subject", 
  cache_table = TRUE
)

variables_df3 <- data.frame(
  variable = c("K200501_001", "K200501_002","K200501_003"),  
  label = c("Total","U.S. citizen", "Not a U.S. citizen")  
)

df3_labeled <- df3 %>%
  left_join(variables_df3, by = "variable")

df3_wide <- df3_labeled %>%
  pivot_wider(names_from = label, values_from = estimate, id_cols = NAME)

# Load necessary libraries
library(ggplot2)
library(tidyr)
library(dplyr)

# Convert df3_wide to long format
df3_long <- df3_wide %>%
  gather(key = "Citizenship", value = "Count", -NAME)

# Calculate total count for each state
df3_long <- df3_long %>%
  group_by(NAME) %>%
  mutate(Total = sum(Count)) %>%
  ungroup()

# Calculate the percentage
df3_long <- df3_long %>%
  mutate(Percentage = (Count / Total) * 100)

# Iterate over each unique citizenship category
for (category in unique(df3_long$Citizenship)) {
  # Filter data for the current citizenship category
  df3_subset <- df3_long %>% 
    filter(Citizenship == category)

  # Generate and print the plot for citizenship
  p <- ggplot(df3_subset, aes(x = NAME, y = Percentage, fill = Citizenship)) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    labs(title = paste("Percentage Distribution of", category, "across States"), 
         x = "State", 
         y = "Percentage")

  print(p)
}




```
The ratio of US Citizens vs Non-US Citizens varies greatly across various states in the U.S. as you can observe from the graph above.In general there is a trend observed that , states with lesser US citizens have a lower employment rate.