---
title: "DF4-Age"
author: "Abhay Prasanna Rao"
date: "2023-12-02"
output: html_document
---

```{r setup_age, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



------------------------------------------------------------------------

## DF4 - Age

```{r}
#Srika
#Age - K200104
df4 <- get_acs(geography = "state", 
                table = "K200104", 
                year = 2021,
                survey = "acs1/subject",cache_table = TRUE
)
variables_df4 <- data.frame(
  variable = c("K200104_001", "K200104_002", "K200104_003", "K200104_004", "K200104_005", "K200104_006", "K200104_007", "K200104_008"),

  label = c("Total_age", "Age_under_18", 
            "Age_18_to_24", "Age_25_to_34", 
            "Age_35_to_44", "Age_45_to_54", "Age_55_to_64","Age_over_64")
)

df4_labeled <- df4 %>%
  left_join(variables_df4, by = "variable")

df4_wide <- df4_labeled %>%
  pivot_wider(names_from = label, values_from = estimate, id_cols = NAME)

```
```{r}
library (plotly)
df4_percentages <- df4_wide %>%
  mutate(
    Age_under_18_Percentage = Age_under_18 / Total_age * 100,
    Age_18_to_24_Percentage = Age_18_to_24 / Total_age * 100,
    Age_25_to_34_Percentage = Age_25_to_34 / Total_age * 100,
    Age_35_to_44_Percentage = Age_35_to_44 / Total_age * 100,
    Age_45_to_54_Percentage = Age_45_to_54 / Total_age * 100,
    Age_55_to_64_Percentage = Age_55_to_64 / Total_age * 100,
    Age_over_64_Percentage = Age_over_64 / Total_age * 100
  )
percentage_columns <- grep("_Percentage$", names(df4_percentages), value = TRUE)
df4_long <- df4_percentages %>%
  pivot_longer(cols = percentage_columns, names_to = "Age_Group", values_to = "Percentage")
plot<-ggplot(df4_long, aes(x = reorder(NAME, -Total_age), y = Percentage, fill = Age_Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Age Distribution by State",
       x = "State",
       y = "Percentage of Total Population",
       fill = "Age Group") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggplotly(plot)
```


```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(RColorBrewer)

# Calculate percentages for each age group
df4_percentages <- df4_wide %>%
  mutate(
    Age_under_18_Percentage = Age_under_18 / Total_age * 100,
    Age_18_to_24_Percentage = Age_18_to_24 / Total_age * 100,
    Age_25_to_34_Percentage = Age_25_to_34 / Total_age * 100,
    Age_35_to_44_Percentage = Age_35_to_44 / Total_age * 100,
    Age_45_to_54_Percentage = Age_45_to_54 / Total_age * 100,
    Age_55_to_64_Percentage = Age_55_to_64 / Total_age * 100,
    Age_over_64_Percentage = Age_over_64 / Total_age * 100
  )

# Filter columns based on names ending with "Percentage"
percentage_columns <- grep("_Percentage$", names(df4_percentages), value = TRUE)

# Reshape the data to a longer format
df4_long <- df4_percentages %>%
  pivot_longer(cols = percentage_columns, names_to = "Age_Group", values_to = "Percentage")

# Create a facet grid for each age group
ggplot(df4_long, aes(x = reorder(NAME, Percentage, mean), y = Percentage, fill = Age_Group)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_grid(Age_Group ~ ., scales = "free_y") +
  labs(title = "Age Distribution by State",
       x = "State",
       y = "Percentage of Total Population",
       fill = "Age Group") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  theme(axis.text.y = element_text(vjust = 0.5, hjust = 1)) +
  scale_fill_brewer(palette = "Dark2") +
  theme(strip.text = element_blank(),
        strip.text.y = element_blank())  # Remove axis titles on the left


```

```{r}
library(ggplot2)

ggplot(df4_percentages, aes(x = reorder(NAME, Age_25_to_34_Percentage, mean), y = Age_25_to_34_Percentage)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Age Distribution by State",
       x = "State",
       y = "Percentage of Population (Age 25-34)")

```

```{r}

ggplot(df4_percentages, aes(x = reorder(NAME, Age_35_to_44_Percentage, mean), y = Age_35_to_44_Percentage)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Age Distribution by State",
       x = "State",
       y = "Percentage of Population (Age 35-44)")
```
```{r}

ggplot(df4_percentages, aes(x = reorder(NAME, Age_45_to_54_Percentage, mean), y = Age_45_to_54_Percentage)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Age Distribution by State",
       x = "State",
       y = "Percentage of Population (Age 45-54)")
```

------------------------------------------------------------------------